# Copyright 2021-2025 ONDEWO GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# ondewo:hand-written-async-service
#
# This file is NOT generated by `make create_async_services`, and the marker above is what stops that
# target from overwriting it. The generator rewrites every ``self.stub.Rpc(...)`` into
# ``await self.stub.Rpc(...)``. That is correct for a unary RPC, because grpc.aio returns an awaitable
# ``UnaryUnaryCall`` -- but ``Sip.SipStreamCallAudio`` is a bidirectional stream, and grpc.aio returns a
# ``StreamStreamCall``, which is an async ITERATOR and must not be awaited. A generated wrapper for it fails
# at runtime on the first call. Because the generator no longer touches this file, a method added to
# ``sip.py`` must be added here by hand as well.
from typing import (
    AsyncIterator,
    Iterator,
    Union,
)

from google.protobuf.empty_pb2 import Empty

from ondewo.sip.client.async_services_interface import AsyncServicesInterface
from ondewo.sip.sip_pb2 import (
    SipCallAudioRequest,
    SipCallAudioResponse,
    SipEndCallRequest,
    SipPlayWavFilesRequest,
    SipRegisterAccountRequest,
    SipReportAnsweringMachineDetectedRequest,
    SipSetCallMediaControlRequest,
    SipStartCallRequest,
    SipStartSessionRequest,
    SipStatus,
    SipStatusHistoryResponse,
    SipTransferCallRequest,
)
from ondewo.sip.sip_pb2_grpc import SipStub


class Sip(AsyncServicesInterface):
    """
    Exposes the sip endpoints of ONDEWO sip in a user-friendly way.

    See sip.proto.
    """

    @property
    def stub(self) -> SipStub:
        stub: SipStub = SipStub(channel=self.grpc_channel)
        return stub

    async def start_session(self, request: SipStartSessionRequest) -> SipStatus:
        response: SipStatus = await self.stub.SipStartSession(request, metadata=self.metadata)
        return response

    async def end_session(self) -> SipStatus:
        response: SipStatus = await self.stub.SipEndSession(Empty(), metadata=self.metadata)
        return response

    async def register_account(self, request: SipRegisterAccountRequest) -> SipStatus:
        response: SipStatus = await self.stub.SipRegisterAccount(request, metadata=self.metadata)
        return response

    async def start_call(self, request: SipStartCallRequest) -> SipStatus:
        response: SipStatus = await self.stub.SipStartCall(request, metadata=self.metadata)
        return response

    async def end_call(self, request: SipEndCallRequest) -> SipStatus:
        response: SipStatus = await self.stub.SipEndCall(request, metadata=self.metadata)
        return response

    async def transfer_call(self, request: SipTransferCallRequest) -> SipStatus:
        response: SipStatus = await self.stub.SipTransferCall(request, metadata=self.metadata)
        return response

    async def get_sip_status(self) -> SipStatus:
        response: SipStatus = await self.stub.SipGetSipStatus(Empty(), metadata=self.metadata)
        return response

    async def get_sip_status_history(self) -> SipStatusHistoryResponse:
        response: SipStatusHistoryResponse = await self.stub.SipGetSipStatusHistory(Empty(), metadata=self.metadata)
        return response

    async def play_wav_files(self, request: SipPlayWavFilesRequest) -> SipStatus:
        response: SipStatus = await self.stub.SipPlayWavFiles(request, metadata=self.metadata)
        return response

    async def mute(self) -> SipStatus:
        response: SipStatus = await self.stub.SipMute(Empty(), metadata=self.metadata)
        return response

    async def un_mute(self) -> SipStatus:
        response: SipStatus = await self.stub.SipUnMute(Empty(), metadata=self.metadata)
        return response

    async def report_answering_machine_detected(self, request: SipReportAnsweringMachineDetectedRequest) -> SipStatus:
        response: SipStatus = await self.stub.SipReportAnsweringMachineDetected(request, metadata=self.metadata)
        return response

    async def set_call_media_control(self, request: SipSetCallMediaControlRequest) -> SipStatus:
        response: SipStatus = await self.stub.SipSetCallMediaControl(request, metadata=self.metadata)
        return response

    def stream_call_audio(
        self,
        request_iterator: Union[AsyncIterator[SipCallAudioRequest], Iterator[SipCallAudioRequest]],
    ) -> AsyncIterator[SipCallAudioResponse]:
        """
        Open the bidirectional live call audio stream.

        This method is deliberately NOT ``async def``: a bidirectional streaming call returns an async
        iterator, not a coroutine. Use it as ``async for response in sip.stream_call_audio(requests)``, and
        call ``.cancel()`` on the returned object to end the stream early.

        Args:
            request_iterator (Union[AsyncIterator[SipCallAudioRequest], Iterator[SipCallAudioRequest]]):
                The requests to send; the first one must carry ``config``.

        Returns:
            AsyncIterator[SipCallAudioResponse]:
                An async iterator over the responses of the stream.
        """
        response_iterator: AsyncIterator[SipCallAudioResponse] = self.stub.SipStreamCallAudio(
            request_iterator,
            metadata=self.metadata,
        )
        return response_iterator
