# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ondewo/sip/sip.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ondewo/sip/sip.proto',
  package='ondewo.sip',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14ondewo/sip/sip.proto\x12\nondewo.sip\x1a\x1bgoogle/protobuf/empty.proto\"P\n\x10StartCallRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x17\n\x0f\x63si_server_host\x18\x02 \x01(\t\x12\x17\n\x0f\x63si_server_port\x18\x03 \x01(\t\"$\n\x11StartCallResponse\x12\x0f\n\x07\x63\x61ll_id\x18\x01 \x01(\t\"@\n\x16RegisterAccountRequest\x12\x14\n\x0c\x61\x63\x63ount_name\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"I\n\x13StartSessionRequest\x12\x14\n\x0c\x61\x63\x63ount_name\x18\x01 \x01(\t\x12\x1c\n\x14\x61uto_answer_interval\x18\x02 \x01(\x05\x32\xf5\x01\n\x0bSipSessions\x12I\n\x0cStartSession\x12\x1f.ondewo.sip.StartSessionRequest\x1a\x16.google.protobuf.Empty\"\x00\x12J\n\tStartCall\x12\x1c.ondewo.sip.StartCallRequest\x1a\x1d.ondewo.sip.StartCallResponse\"\x00\x12O\n\x0fRegisterAccount\x12\".ondewo.sip.RegisterAccountRequest\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_STARTCALLREQUEST = _descriptor.Descriptor(
  name='StartCallRequest',
  full_name='ondewo.sip.StartCallRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ondewo.sip.StartCallRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='csi_server_host', full_name='ondewo.sip.StartCallRequest.csi_server_host', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='csi_server_port', full_name='ondewo.sip.StartCallRequest.csi_server_port', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=145,
)


_STARTCALLRESPONSE = _descriptor.Descriptor(
  name='StartCallResponse',
  full_name='ondewo.sip.StartCallResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='call_id', full_name='ondewo.sip.StartCallResponse.call_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=147,
  serialized_end=183,
)


_REGISTERACCOUNTREQUEST = _descriptor.Descriptor(
  name='RegisterAccountRequest',
  full_name='ondewo.sip.RegisterAccountRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='account_name', full_name='ondewo.sip.RegisterAccountRequest.account_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='password', full_name='ondewo.sip.RegisterAccountRequest.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=185,
  serialized_end=249,
)


_STARTSESSIONREQUEST = _descriptor.Descriptor(
  name='StartSessionRequest',
  full_name='ondewo.sip.StartSessionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='account_name', full_name='ondewo.sip.StartSessionRequest.account_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='auto_answer_interval', full_name='ondewo.sip.StartSessionRequest.auto_answer_interval', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=251,
  serialized_end=324,
)

DESCRIPTOR.message_types_by_name['StartCallRequest'] = _STARTCALLREQUEST
DESCRIPTOR.message_types_by_name['StartCallResponse'] = _STARTCALLRESPONSE
DESCRIPTOR.message_types_by_name['RegisterAccountRequest'] = _REGISTERACCOUNTREQUEST
DESCRIPTOR.message_types_by_name['StartSessionRequest'] = _STARTSESSIONREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StartCallRequest = _reflection.GeneratedProtocolMessageType('StartCallRequest', (_message.Message,), {
  'DESCRIPTOR' : _STARTCALLREQUEST,
  '__module__' : 'ondewo.sip.sip_pb2'
  # @@protoc_insertion_point(class_scope:ondewo.sip.StartCallRequest)
  })
_sym_db.RegisterMessage(StartCallRequest)

StartCallResponse = _reflection.GeneratedProtocolMessageType('StartCallResponse', (_message.Message,), {
  'DESCRIPTOR' : _STARTCALLRESPONSE,
  '__module__' : 'ondewo.sip.sip_pb2'
  # @@protoc_insertion_point(class_scope:ondewo.sip.StartCallResponse)
  })
_sym_db.RegisterMessage(StartCallResponse)

RegisterAccountRequest = _reflection.GeneratedProtocolMessageType('RegisterAccountRequest', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERACCOUNTREQUEST,
  '__module__' : 'ondewo.sip.sip_pb2'
  # @@protoc_insertion_point(class_scope:ondewo.sip.RegisterAccountRequest)
  })
_sym_db.RegisterMessage(RegisterAccountRequest)

StartSessionRequest = _reflection.GeneratedProtocolMessageType('StartSessionRequest', (_message.Message,), {
  'DESCRIPTOR' : _STARTSESSIONREQUEST,
  '__module__' : 'ondewo.sip.sip_pb2'
  # @@protoc_insertion_point(class_scope:ondewo.sip.StartSessionRequest)
  })
_sym_db.RegisterMessage(StartSessionRequest)



_SIPSESSIONS = _descriptor.ServiceDescriptor(
  name='SipSessions',
  full_name='ondewo.sip.SipSessions',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=327,
  serialized_end=572,
  methods=[
  _descriptor.MethodDescriptor(
    name='StartSession',
    full_name='ondewo.sip.SipSessions.StartSession',
    index=0,
    containing_service=None,
    input_type=_STARTSESSIONREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='StartCall',
    full_name='ondewo.sip.SipSessions.StartCall',
    index=1,
    containing_service=None,
    input_type=_STARTCALLREQUEST,
    output_type=_STARTCALLRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='RegisterAccount',
    full_name='ondewo.sip.SipSessions.RegisterAccount',
    index=2,
    containing_service=None,
    input_type=_REGISTERACCOUNTREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SIPSESSIONS)

DESCRIPTOR.services_by_name['SipSessions'] = _SIPSESSIONS

# @@protoc_insertion_point(module_scope)
